"""table creation62

Revision ID: 5829d2a774a6
Revises: 
Create Date: 2024-09-23 11:53:11.156925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5829d2a774a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursemodules',
    sa.Column('modulesid', sa.Integer(), nullable=False),
    sa.Column('modulename', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('modulesid')
    )
    op.create_table('enquirystatus',
    sa.Column('enquirys_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('enquirys_id')
    )
    op.create_table('qualifications',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('qualification_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_table('resources',
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.Column('resourcename', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('resourceid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('firstname', sa.String(length=150), nullable=False),
    sa.Column('lastname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('highest_qualificationid', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('yearofgraduation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highest_qualificationid'], ['qualifications.qualification_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('enquiries',
    sa.Column('enqid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('enquiry_date', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=150), nullable=True),
    sa.Column('statusid', sa.Integer(), nullable=False),
    sa.Column('resourceid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resourceid'], ['resources.resourceid'], ),
    sa.ForeignKeyConstraint(['statusid'], ['enquirystatus.enquirys_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('enqid')
    )
    op.create_table('courses',
    sa.Column('courseid', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('course_duration', sa.Integer(), nullable=False),
    sa.Column('fees', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('moduleid', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.enqid'], ),
    sa.ForeignKeyConstraint(['moduleid'], ['coursemodules.modulesid'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.qualification_id'], ),
    sa.PrimaryKeyConstraint('courseid'),
    sa.UniqueConstraint('coursename'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('enquiries')
    op.drop_table('user')
    op.drop_table('resources')
    op.drop_table('qualifications')
    op.drop_table('enquirystatus')
    op.drop_table('coursemodules')
    # ### end Alembic commands ###
