"""table creation1

Revision ID: e51f9d823c8f
Revises: 
Create Date: 2024-09-21 17:11:21.253661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51f9d823c8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('highest_qualification', sa.String(length=200), nullable=False))
        batch_op.drop_constraint('FK__users__highest_q__59FA5E80', type_='foreignkey')
        batch_op.drop_column('highest_qualificationid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_qualificationid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('FK__users__highest_q__59FA5E80', 'qualifications', ['highest_qualificationid'], ['qualification_id'])
        batch_op.drop_column('highest_qualification')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
