"""table creation2

Revision ID: f1757c3a431b
Revises: e51f9d823c8f
Create Date: 2024-09-21 17:20:05.666380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1757c3a431b'
down_revision = 'e51f9d823c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_qualificationid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'qualifications', ['highest_qualificationid'], ['qualification_id'])
        batch_op.drop_column('highest_qualification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_qualification', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('highest_qualificationid')

    # ### end Alembic commands ###
